spring.application.name=quanlydoan
spring.datasource.url=jdbc:mysql://localhost:3306/quanlydoan
spring.datasource.username=root
spring.datasource.password=Son20062004
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.id.new_generator_mappings=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.main.lazy-initialization=true

springdoc.swagger-ui.path=/swagger-ui-custom.html
springdoc.swagger-ui.operationsSorter=method
springdoc.api-docs.path=/api-docs


# Hi?n t?t c? c�c log c?a package jwt
logging.level.com.web.jwt=DEBUG

logging.level.root=INFO

spring.thymeleaf.prefix=/views/
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.template-resolver-order=1


url.frontend=http://localhost:8080

# Gemini AI API Configuration
gemini.api.key=AIzaSyCYQJitZWbX9d-Pmh0N916ZFzgZDLA4wFw


